### ISSUE TITLE
What's the SwitchOp?

### ISSUE THREAD

**Issue by dangbo** [LiangKlausQiu/GRU_Android#2]
Hello, I noticed that you add a new op called "SwitchOp", but I can't find implement of it. Can you tell me what should I do now? 

> In Android, some of the operators are disabled for computing efficiency. However, we may have these ops or even some new ops in our inference graph. In this case, while loading the graph, Android will complain: No Op Kenel was registered to support Op ‘Some Op’.
So it’s necessary to look up or write the C++ implementation file corresponding to each op and register them in tensorflow/core/kenels/BUILD.

**Comment by Liang-Qiu** [comment]
Hi, I think you should be able to find the implementation in kenels. The name may not be exaclty SwiychOp but something related.

**Comment by dangbo** [comment]
Thx
